name: contact_project
version: 0.0.1
author: Your Name
description: contact_project application that uses dartling for its model.
homepage: http://ondart.me/
dependencies:
  browser: any
  dartling: any
  dartling_default_app: any
